# Generated by Django 5.2.3 on 2025-07-07 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_category_deleted_on_alter_comment_deleted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='forum.category'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_locked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
