# Generated by Django 5.2.3 on 2025-07-08 04:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_category_parent_alter_thread_is_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_on'], 'permissions': [('can_lock', 'Can Lock')]},
        ),
        migrations.AddField(
            model_name='thread',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.forum'),
            preserve_default=False,
        ),
    ]
