# Generated by Django 5.2.3 on 2025-07-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_thread_options_thread_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
