# Generated by Django 5.2.3 on 2025-07-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_comment_content_alter_thread_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='This category does not have any description.'),
        ),
        migrations.AddField(
            model_name='forum',
            name='description',
            field=models.TextField(default='This category does not have any descripiton.'),
        ),
    ]
